services:
  app:
    build: .
    command: sh -c "bundle exec rake db:migrate && bundle exec rails s"
    ports:
      - 3003:3000
    volumes:
      - bundler_gems:/usr/local/bundle/
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
volumes:
  mysql:
  bundler_gems:
