services:
  app:
    build: .
    command: sh -c "bundle exec rake db:create && bundle exec rails s"
    ports:
      - 3003:3000
    volumes:
      - .:/myapp
      - bundler_gems:/usr/local/bundle/
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
