development:
  adapter: mysql2
  database: mbeurr_development
  pool: 5
  timeout: 5000
  host: db
  password: password
  username: root

test:
  adapter: mysql2
  database: mbeurr_test
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  password: password
  username: root
